components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  title: Gen3 OpenAI Wrapper Service
  version: 0.1.0
openapi: 3.0.2
paths:
  /:
    get:
      description: ''
      operationId: read_root__get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Read Root
  /_status:
    get:
      description: ''
      operationId: get_status__status_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Get Status
  /ask/:
    get:
      description: ''
      operationId: ask_ask__get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Ask
    post:
      description: ''
      operationId: ask_ask__post
      parameters:
      - in: query
        name: topic
        required: false
        schema:
          default: default
          title: Topic
          type: string
      requestBody:
        content:
          application/json:
            schema:
              title: Data
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Ask
  /ask/{topic}:
    post:
      description: ''
      operationId: ask_ask__topic__post
      parameters:
      - in: path
        name: topic
        required: true
        schema:
          title: Topic
          type: string
      requestBody:
        content:
          application/json:
            schema:
              title: Data
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Ask
  /version:
    get:
      description: ''
      operationId: get_version_version_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Get Version
